# fake db config yml and test env for Travis CI
development: &db
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: devhub_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  <<: *db
  database: devhub_test
  username: travis

production:
  <<: *db
  database: devhub_production
